[build]
builder = "maven"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/entrepreneur-platform-0.0.1-SNAPSHOT.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3